steps:
  - name: build-and-test-iri-oracle8
    command: mvn integration-test -Dlogging-level=INFO && mv target/iri*.jar target/iri-oracle8.jar && java -version && java -version
    plugins:
      docker#v1.3.0:
        image: "iotacafe/iri-build-env:oracle8u171-1-maven3.5.3-1"
    artifact_paths:
      - target/iri-oracle8.jar
    agents:
      queue: ops

  - name: build-and-test-iri-openjdk8
    command: mvn integration-test -Dlogging-level=INFO && mv target/iri*.jar target/iri-oracle8.jar && java -version && java -version
    plugins:
      docker#v1.3.0:
        image: "iotacafe/iri-build-env:openjdk8-maven3.5.3-1"
    artifact_paths:
      - target/iri-oracle8.jar
    agents:
      queue: ops

  - wait

